name: Build Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        nim: ["binary:2.2.2"]
    uses: ./.github/workflows/runner-main.yaml
    with:
      container: 'attioemailtracking'
      release: 'main'
      nimversion: ${{ matrix.nim }}
    secrets: inherit

