name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        nim: ["binary:1.6.18"]
    uses: ./.github/workflows/runner-main.yaml
    with:
      container: 'attioemailtracking'
      release: 'prod'
      nimversion: ${{ matrix.nim }}
    secrets: inherit
